### ISSUE TITLE
Add unicode input method

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/atom-language-redprl#6]

**Comment by ak3n** [comment]
Maybe there is a point to move it to a new package (redprl-mode) like agda-mode and language-agda?

**Comment by freebroccolo** [comment]
Are you thinking of a basic package and then something separate for the fancier interactive stuff?

If so, it's a possibility although I'm not sure it's worth it since I think having two packages creates some unnecessary confusion. In the case of agda, if I had been a better maintainer there probably wouldn't have been a need to create an entirely separate package.

Now, as far as an independent unicode input method is concerned, I think that's not a bad idea. In fact, this is the sort of thing you would fit nicely with the [services API](http://blog.atom.io/2015/03/25/new-services-API.html). There may already be a suitable package for this too.

**Comment by jonsterling** [comment]
Personally, I'd err on the side of an integrated solution rather than a completely modular solution...

**Comment by ak3n** [comment]
@freebroccolo 

>Are you thinking of a basic package and then something separate for the fancier interactive stuff?

Yes, as I understood most "language-<name>" atom packages are only for syntax highlighting, but maybe it's better to use one big package.

**Comment by freebroccolo** [comment]
I've created a package for unicode input [here](https://github.com/freebroccolo/atom-input-assist). It loads JSON encoded trees which correspond to the quail input methods that emacs supports and it provides completions through the [autocomplete-plus](https://github.com/atom/autocomplete-plus) API.
